### ISSUE TITLE
Skins not loading on develop branch

### ISSUE THREAD

**Issue by notabirb1** [betacraftuk/legacyfix#11]
**Sorry for the non-issue(?) issue report.**

I was trying Legacyfix out for the first time and, while sound worked fine on every version I tried, I was only able to get my skin to load on `b1.9-pre3` and `a1.1.2_01`. (I also tried `a.1.26`, `b1.3_01`, `b1.7.3`, and `r1.5.2`)

Based on the status listed on the readme, I'm assuming skin support is unfinished, so I'd just like to check if this is an issue on my end or an unfinished feature of Legacyfix.

If it helps, I'm using Prism Launcher with the java arguments to set the java agent to Legacyfix. I can post my log files if necessary.

**Comment by notdevcody** [comment]
Only the [`stable`](https://github.com/betacraftuk/legacyfix/tree/stable) branch has support for them as of now.
Could you provide some logs on the versions you couldn't get it to work?

**Comment by notabirb1** [comment]
Apparently, I did not notice there were multiple branches! That would explain why LegacyFix didn't work, as I was using the GitHub Actions build of the [`develop`](/betacraftuk/legacyfix/tree/develop) branch.

Not sure if they're still necessary, but here are my logs for each version (I have given the PrismLauncher flatpak permission to access the directory containing LegacyFix):
<details>
<summary>a1.2.6</summary>

```
Prism Launcher version: 8.4 (flatpak)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [removed]

session.minecraft.net resolves to:
    [removed]

textures.minecraft.net resolves to:
    [removed]

api.mojang.com resolves to:
    [removed]


Minecraft folder is:
/home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/a1.2.6/.minecraft


Java path is:
/app/jdk/8/jre/bin/java


Java is version 1.8.0_412, using 64 (amd64) architecture, from Oracle Corporation.


Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz
NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 375c

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 555.58.02

Main Class:
  

Native path:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/a1.2.6/natives

Traits:
traits texturepacks
traits legacyLaunch
traits legacyServices

Libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/a1.2.6/minecraft-a1.2.6-client.jar

Native libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
    --gameDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/a1.2.6/.minecraft --assetsDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/a1.2.6/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -Djava.util.Arrays.useLegacyMergeSort=true, -javaagent:/home/notabirb1/Programs/legacyfix-2.0.jar, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 2390


[LF] INFO: Loading build 2.0-14.06.2024
[LF] ERROR: Patch open texture pack folder button
        javassist.CannotCompileException: [source error] getMethod(java.lang.String) not found in java.lang.Class
28
Setting user: notabirb1, token:<ACCESS TOKEN>:<PROFILE ID>
Jul 16, 2024 8:16:59 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)



Starting up SoundSystem...
Jul 16, 2024 8:16:59 PM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers

Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at java.net.URL.openStream(URL.java:1093)
	at bn.run(SourceFile:28)
Player is null
Player is null
Player is now null
Loading texture http://www.minecraft.net/skin/notabirb1.png
Player count: 1
Player is bq@26
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 0.
```
</details>


<details>
<summary>b1.3_01</summary>

```
Prism Launcher version: 8.4 (flatpak)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [removed]

session.minecraft.net resolves to:
    [removed]

textures.minecraft.net resolves to:
    [removed]

api.mojang.com resolves to:
    [removed]


Minecraft folder is:
/home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.3_01/.minecraft


Java path is:
/app/jdk/8/jre/bin/java


Java is version 1.8.0_412, using 64 (amd64) architecture, from Oracle Corporation.


Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz
NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 375c

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 555.58.02

Main Class:
  

Native path:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.3_01/natives

Traits:
traits texturepacks
traits legacyLaunch
traits legacyServices

Libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/b1.3_01/minecraft-b1.3_01-client.jar

Native libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
    --gameDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.3_01/.minecraft --assetsDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.3_01/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -Djava.util.Arrays.useLegacyMergeSort=true, -javaagent:/home/notabirb1/Programs/legacyfix-2.0.jar, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 2330


[LF] INFO: Loading build 2.0-14.06.2024
[LF] ERROR: Patch open texture pack folder button
        javassist.CannotCompileException: [source error] getMethod(java.lang.String) not found in java.lang.Class
28
Setting user: notabirb1, token:<ACCESS TOKEN>:<PROFILE ID>
Jul 16, 2024 8:15:42 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)


Jul 16, 2024 8:15:42 PM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers


Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at java.net.URL.openStream(URL.java:1093)
	at bz.run(SourceFile:28)
143 recipes
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7f765c02f340 serial: 7623 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxDisplay.nDestroyWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.destroyWindow(LinuxDisplay.java:592)
	at org.lwjgl.opengl.Display.destroyWindow(Display.java:351)
	at org.lwjgl.opengl.Display.access$400(Display.java:65)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.d(SourceFile:511)
	at net.minecraft.client.Minecraft.run(SourceFile:743)
	at java.lang.Thread.run(Thread.java:750)
Process exited with code 0.
```
</details>

<details>
<summary>b1.7.3</summary>

```
Prism Launcher version: 8.4 (flatpak)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [removed]

session.minecraft.net resolves to:
    [removed]

textures.minecraft.net resolves to:
    [removed]

api.mojang.com resolves to:
    [removed]


Minecraft folder is:
/home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.7.3/.minecraft


Java path is:
/app/jdk/8/jre/bin/java


Java is version 1.8.0_412, using 64 (amd64) architecture, from Oracle Corporation.


Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz
NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 375c

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 555.58.02

Main Class:
  

Native path:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.7.3/natives

Traits:
traits texturepacks
traits legacyLaunch
traits legacyServices

Libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
    --gameDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.7.3/.minecraft --assetsDir /home/notabirb1/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/b1.7.3/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-javaagent:/home/notabirb1/Programs/legacyfix-2.0.jar, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 2556


[LF] INFO: Loading build 2.0-14.06.2024
[LF] ERROR: Patch open texture pack folder button
        javassist.CannotCompileException: [source error] getMethod(java.lang.String) not found in java.lang.Class
16 achievements
151 recipes
Setting user: notabirb1, token:<ACCESS TOKEN>:<PROFILE ID>
Jul 16, 2024 8:22:35 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)


Jul 16, 2024 8:22:35 PM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers


Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at java.net.URL.openStream(URL.java:1093)
	at cz.run(SourceFile:28)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7fb90802dec0 serial: 22240 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxDisplay.nDestroyWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.destroyWindow(LinuxDisplay.java:592)
	at org.lwjgl.opengl.Display.destroyWindow(Display.java:351)
	at org.lwjgl.opengl.Display.access$400(Display.java:65)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.d(SourceFile:588)
	at net.minecraft.client.Minecraft.run(SourceFile:848)
	at java.lang.Thread.run(Thread.java:750)
Process exited with code 0.

```
</details>

Sorry for wasting your time!

**Comment by notdevcody** [comment]
Leaving this open until this feature is reimplemented.
