### ISSUE TITLE
Fullscreen issues

### ISSUE THREAD

**Issue by Moresteck** [betacraftuk/legacyfix#13]
### Windows
- game over-fullscreening (e.g. shows only 2/3 of the game's view)
- game under-fullscreening (e.g. fills only 2/3s of the screen)
### Linux
- not fullscreening[^1]
- crashing[^2] — setting `__GL_THREADED_OPTIMIZATIONS` to `0` fixes the issue
- black screening
- perhaps over/under-fullscreening
### macOS
- white screening
- under-fullscreening

[^1]: On Xorg, fullscreen can take many many presses to trigger.
[^2]: Crash affects Wayland, (user config: Fedora Linux with KDE Plasma, Nvidia drivers 560+)
    `(12:10:19) #`
    `(12:10:19) # A fatal error has been detected by the Java Runtime Environment:`
    `(12:10:19) #`
    `(12:10:19) #  SIGBUS (0x7) at pc=0x00007f403a0387cc, pid=14805, tid=0x00007f40475ff6c0`
    `(12:10:19) #`
    `(12:10:19) # JRE version: OpenJDK Runtime Environment (8.0_422-b05) (build 1.8.0_422-b05)`
    `(12:10:19) # Java VM: OpenJDK 64-Bit Server VM (25.422-b05 mixed mode linux-amd64 compressed oops)`
    `(12:10:19) # Problematic frame:`
    `(12:10:19) # C  [libnvidia-glcore.so.560.35.03+0xa387cc]`
    `(12:10:19) #`
    `(12:10:19) # Core dump written. Default location: /home/<user>/.betacraft/default instance/core or core.14805`
    `(12:10:19) #`
    `(12:10:19) # An error report file with more information is saved as:`
    `(12:10:19) # /home/<user>/.betacraft/default instance/hs_err_pid14805.log`
    `(12:10:19) #`
    `(12:10:19) # If you would like to submit a bug report, please visit:`
    `(12:10:19) #   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-1.8.0-openjdk&version=39`
    `(12:10:19) # The crash happened outside the Java Virtual Machine in native code.`
    `(12:10:19) # See problematic frame for where to report the bug.`
    `(12:10:19) #`

**Comment by jdj212223-ctrl** [comment]
same but not fatal error but org.lwjgl.LWJGLException: Native cursors not supported
	at org.lwjgl.input.Cursor.<init>(Cursor.java:88)
	at md.<init>(SourceFile:32)
	at net.minecraft.client.Minecraft.a(SourceFile:219)
	at net.minecraft.client.Minecraft.run(SourceFile:555)
	at java.lang.Thread.run(Thread.java:750)
Jun 12, 2026 8:00:28 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.OSXEnvironmentPlugin
Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.
 so im on mac ofc
