### ISSUE TITLE
ModLoader.addArmor in ML b1.8.1 seems to be broken in Java 9+

### ISSUE THREAD

**Issue by forkiesassds** [betacraftuk/legacyfix#3]
I'm not sure if this was fixed by now, but here's the log.

```
java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: qz.j/[Ljava.lang.String;/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:167)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.get(Field.java:428)
	at ModLoader.AddArmor(ModLoader.java:217)
	at mod_IC2.<clinit>(mod_IC2.java:150)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
	at java.base/java.lang.Class.newInstance(Class.java:677)
	at ModLoader.addMod(ModLoader.java:275)
	at ModLoader.readFromModFolder(ModLoader.java:1179)
	at ModLoader.init(ModLoader.java:824)
	at ModLoader.AddAllRenderers(ModLoader.java:186)
	at aam.<init>(aam.java:61)
	at aam.<clinit>(aam.java:10)
	at net.minecraft.client.Minecraft.a(SourceFile:259)
	at net.minecraft.client.Minecraft.run(SourceFile:629)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessException: static final field has no write access: qz.j/[Ljava.lang.String;/putStatic, from class java.lang.Object (module java.base)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:955)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3494)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3485)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1637)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:145)
	... 25 more```

**Comment by forkiesassds** [comment]
This seems to affect more than simply ModLoader.AddArmor.

**Comment by Lassebq** [comment]
Not sure how that's related to legacyfix. Reflection is just not capable of doing it after a certain java version

**Comment by forkiesassds** [comment]
> Not sure how that's related to legacyfix. Reflection is just not capable of doing it after a certain java version

Well it's supposed to fix incompatibility issues with newer Java, especially Java 9+.

**Comment by notdevcody** [comment]
A patch is available in both the stable and develop branches.
