### ISSUE TITLE
when i open my inventory or menu it crashes the game {m1 apple silicon mac}

### ISSUE THREAD

**Issue by oofy123** [betacraftuk/legacyfix#8]
there are also two windows open. one is "null" and it displays minecraft. one is "minecraft", it displays nothing.

**Comment by oofy123** [comment]
note: it only happens when the legacyfix is in use. otherwise it works fine. {with the colors messed up tho}

**Comment by onkoe** [comment]
Same issue here. Here's a system report and the logs: 

System report: 
[MacBook Pro.spx.txt](https://github.com/betacraftuk/legacyfix/files/15461997/MacBook.Pro.spx.txt)


Logs: 

```
Prism Launcher version: 8.3 (official)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [****:****:****:****:****:****:****:****, **.**.**.**]

textures.minecraft.net resolves to:
    [****:****:****:****:****:****:****:****, **.**.**.**]

api.mojang.com resolves to:
    [****:****:****:****:****:****:****:****, **.**.**.**]


Minecraft folder is:
/Users/********/Library/Application Support/PrismLauncher/instances/b1.7.3/.minecraft


Java path is:
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java


Checking Java version...
Java is version 1.8.0_352, using 64 (aarch64) architecture, from Azul Systems, Inc..


Main Class:
  

Native path:
  /Users/********/Library/Application Support/PrismLauncher/instances/b1.7.3/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /Users/********/Library/Application Support/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx-arm64.jar
  /Users/********/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx-arm64.jar

Params:
  

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-Dlf.deAWT=true, -javaagent:/Users/********/Library/Application Support/PrismLauncher/libraries/uk/betacraft/legacyfix/nightly-7ff1a85/legacyfix-nightly-7ff1a85.jar, -Xdock:icon=icon.png, -Xdock:name="Prism Launcher: b1.7.3", -Xms1600m, -Xmx16000m, -Duser.language=en]


Minecraft process ID: 58768


patchmacmouse - false
fix15a - false
deAWT - true
found mcclas: net.minecraft.client.Minecraft
found appletMode field: n
found canvas class name: r
found match for guiscreen: da
found resolution: d
found resolution: e
16 achievements
151 recipes
Setting user: smx, token:<ACCESS TOKEN>:<PROFILE ID>
May 27, 2024 4:49:35 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.OSXEnvironmentPlugin
May 27, 2024 4:49:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

May 27, 2024 4:49:35 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174


Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
	at java.net.URL.openStream(URL.java:1093)
	at cz.run(SourceFile:28)
java.lang.NullPointerException
	at vy.b(SourceFile:79)
	at net.minecraft.client.Minecraft.h(SourceFile:1054)
	at net.minecraft.client.Minecraft.a(SourceFile:535)
	at net.minecraft.client.Minecraft.i(SourceFile:1061)
	at net.minecraft.client.Minecraft.k(SourceFile:1375)
	at net.minecraft.client.Minecraft.run(SourceFile:754)
	at java.lang.Thread.run(Thread.java:750)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Log upload triggered at: 27 May 2024 16:51:35 -0500
```

**Comment by Moresteck** [comment]
You didn't include `-Dlf.patchMouse` in your JVM arguments.

**Comment by onkoe** [comment]
That worked, thank you! :)
